/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MonsterToken } from "./MonsterToken";
export type { SimpleMonsterToken } from "./SimpleMonsterToken";
