/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleHtlcSol from "./SimpleHTLC.sol";
export type { simpleHtlcSol };
export type { DragonToken } from "./DragonToken";
export type { MonsterToken } from "./MonsterToken";
export type { SimpleMonsterToken } from "./SimpleMonsterToken";
