/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MaliciousReentrancyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attacked"
      | "attemptReentrancy"
      | "htlc"
      | "preimage"
      | "targetContract"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "attacked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "attemptReentrancy",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "htlc", values?: undefined): string;
  encodeFunctionData(functionFragment: "preimage", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "targetContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "attacked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attemptReentrancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "htlc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "preimage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "targetContract",
    data: BytesLike
  ): Result;
}

export interface MaliciousReentrancy extends BaseContract {
  connect(runner?: ContractRunner | null): MaliciousReentrancy;
  waitForDeployment(): Promise<this>;

  interface: MaliciousReentrancyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attacked: TypedContractMethod<[], [boolean], "view">;

  attemptReentrancy: TypedContractMethod<
    [_contractId: BytesLike, _preimage: BytesLike],
    [void],
    "nonpayable"
  >;

  htlc: TypedContractMethod<[], [string], "view">;

  preimage: TypedContractMethod<[], [string], "view">;

  targetContract: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attacked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "attemptReentrancy"
  ): TypedContractMethod<
    [_contractId: BytesLike, _preimage: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "htlc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "preimage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "targetContract"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
