/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SwapSageHTLCv2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "fund"
      | "getCurrentTime"
      | "getDetails"
      | "isClaimable"
      | "isRefundable"
      | "isTrustedForwarder"
      | "owner"
      | "refund"
      | "renounceOwnership"
      | "setTrustedForwarder"
      | "swaps"
      | "transferOwnership"
      | "trustedForwarder"
      | "trustedForwarders"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "Funded"
      | "OwnershipTransferred"
      | "Refunded"
      | "TrustedForwarderUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fund",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRefundable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedForwarder",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "swaps", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarders",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDetails", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRefundable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swaps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarders",
    data: BytesLike
  ): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    contractId: BytesLike,
    beneficiary: AddressLike,
    preimage: BytesLike,
    value: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    beneficiary: string,
    preimage: string,
    value: bigint
  ];
  export interface OutputObject {
    contractId: string;
    beneficiary: string;
    preimage: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundedEvent {
  export type InputTuple = [
    contractId: BytesLike,
    originator: AddressLike,
    beneficiary: AddressLike,
    token: AddressLike,
    value: BigNumberish,
    hashLock: BytesLike,
    timelock: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    originator: string,
    beneficiary: string,
    token: string,
    value: bigint,
    hashLock: string,
    timelock: bigint
  ];
  export interface OutputObject {
    contractId: string;
    originator: string;
    beneficiary: string;
    token: string;
    value: bigint;
    hashLock: string;
    timelock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    contractId: BytesLike,
    originator: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    originator: string,
    value: bigint
  ];
  export interface OutputObject {
    contractId: string;
    originator: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedForwarderUpdatedEvent {
  export type InputTuple = [forwarder: AddressLike, trusted: boolean];
  export type OutputTuple = [forwarder: string, trusted: boolean];
  export interface OutputObject {
    forwarder: string;
    trusted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwapSageHTLCv2 extends BaseContract {
  connect(runner?: ContractRunner | null): SwapSageHTLCv2;
  waitForDeployment(): Promise<this>;

  interface: SwapSageHTLCv2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<
    [_contractId: BytesLike, _preimage: BytesLike],
    [void],
    "nonpayable"
  >;

  fund: TypedContractMethod<
    [
      _contractId: BytesLike,
      _token: AddressLike,
      _beneficiary: AddressLike,
      _hashLock: BytesLike,
      _timelock: BigNumberish,
      _value: BigNumberish
    ],
    [void],
    "payable"
  >;

  getCurrentTime: TypedContractMethod<[], [bigint], "view">;

  getDetails: TypedContractMethod<
    [_contractId: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        token: string;
        beneficiary: string;
        originator: string;
        hashLock: string;
        timelock: bigint;
        value: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  isClaimable: TypedContractMethod<[_contractId: BytesLike], [boolean], "view">;

  isRefundable: TypedContractMethod<
    [_contractId: BytesLike],
    [boolean],
    "view"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[_contractId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike, trusted: boolean],
    [void],
    "nonpayable"
  >;

  swaps: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        token: string;
        beneficiary: string;
        originator: string;
        hashLock: string;
        timelock: bigint;
        value: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedForwarder: TypedContractMethod<[], [string], "view">;

  trustedForwarders: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [_contractId: BytesLike, _preimage: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<
    [
      _contractId: BytesLike,
      _token: AddressLike,
      _beneficiary: AddressLike,
      _hashLock: BytesLike,
      _timelock: BigNumberish,
      _value: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getCurrentTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDetails"
  ): TypedContractMethod<
    [_contractId: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        token: string;
        beneficiary: string;
        originator: string;
        hashLock: string;
        timelock: bigint;
        value: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isClaimable"
  ): TypedContractMethod<[_contractId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRefundable"
  ): TypedContractMethod<[_contractId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[_contractId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTrustedForwarder"
  ): TypedContractMethod<
    [forwarder: AddressLike, trusted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swaps"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        token: string;
        beneficiary: string;
        originator: string;
        hashLock: string;
        timelock: bigint;
        value: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedForwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "trustedForwarders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedForwarderUpdated"
  ): TypedContractEvent<
    TrustedForwarderUpdatedEvent.InputTuple,
    TrustedForwarderUpdatedEvent.OutputTuple,
    TrustedForwarderUpdatedEvent.OutputObject
  >;

  filters: {
    "Claimed(bytes32,address,bytes32,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Funded(bytes32,address,address,address,uint256,bytes32,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Refunded(bytes32,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "TrustedForwarderUpdated(address,bool)": TypedContractEvent<
      TrustedForwarderUpdatedEvent.InputTuple,
      TrustedForwarderUpdatedEvent.OutputTuple,
      TrustedForwarderUpdatedEvent.OutputObject
    >;
    TrustedForwarderUpdated: TypedContractEvent<
      TrustedForwarderUpdatedEvent.InputTuple,
      TrustedForwarderUpdatedEvent.OutputTuple,
      TrustedForwarderUpdatedEvent.OutputObject
    >;
  };
}
