/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MonsterToken__factory } from "./MonsterToken__factory";
export { SimpleMonsterToken__factory } from "./SimpleMonsterToken__factory";
