/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MaliciousReentrancy,
  MaliciousReentrancyInterface,
} from "../../contracts/MaliciousReentrancy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_htlc",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "attacked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_contractId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_preimage",
        type: "bytes32",
      },
    ],
    name: "attemptReentrancy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "htlc",
    outputs: [
      {
        internalType: "contract SwapSageHTLC",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "preimage",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "targetContract",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60806040526003805460ff1916905534801561001a57600080fd5b506040516103023803806103028339810160408190526100399161005e565b600080546001600160a01b0319166001600160a01b039290921691909117905561008e565b60006020828403121561007057600080fd5b81516001600160a01b038116811461008757600080fd5b9392505050565b6102658061009d6000396000f3fe60806040526004361061004e5760003560e01c80631105f941146100de578063bd90df701461010d578063bddc65f914610131578063e4b23d0c14610147578063fd10037f1461017f57600080fd5b366100d95760035460ff166100d7576003805460ff1916600190811790915560005490546002546040516384cc9dfb60e01b8152600481019290925260248201526001600160a01b03909116906384cc9dfb90604401600060405180830381600087803b1580156100be57600080fd5b505af11580156100d2573d6000803e3d6000fd5b505050505b005b600080fd5b3480156100ea57600080fd5b506003546100f89060ff1681565b60405190151581526020015b60405180910390f35b34801561011957600080fd5b5061012360015481565b604051908152602001610104565b34801561013d57600080fd5b5061012360025481565b34801561015357600080fd5b50600054610167906001600160a01b031681565b6040516001600160a01b039091168152602001610104565b34801561018b57600080fd5b506100d761019a36600461020d565b600182905560028190556000546040516384cc9dfb60e01b815260048101849052602481018390526001600160a01b03909116906384cc9dfb90604401600060405180830381600087803b1580156101f157600080fd5b505af1158015610205573d6000803e3d6000fd5b505050505050565b6000806040838503121561022057600080fd5b5050803592602090910135915056fea26469706673582212205bdb0e8f265648b6cb3408035b33c85639603a62cccace4305ac4a4116cfbfd764736f6c63430008180033";

type MaliciousReentrancyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousReentrancyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousReentrancy__factory extends ContractFactory {
  constructor(...args: MaliciousReentrancyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _htlc: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_htlc, overrides || {});
  }
  override deploy(
    _htlc: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_htlc, overrides || {}) as Promise<
      MaliciousReentrancy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MaliciousReentrancy__factory {
    return super.connect(runner) as MaliciousReentrancy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousReentrancyInterface {
    return new Interface(_abi) as MaliciousReentrancyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousReentrancy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MaliciousReentrancy;
  }
}
